{
 "title": "HealthCare_DashBoard",
 "time": { "from": "2018-11-01T00:00:00.000Z", "to": "2023-10-30T00:00:00.000Z" },
 "panels": [
  {
   "title": "Length of Stay",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "collapsed": true,
   "panels": [
    {
     "title": "Average Length of Stay",
     "type": "gauge",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "dataset": "health_care_dataset",
       "rawSql": "\r\nSELECT round(AVG(DATEDIFF(DischargeDate_new, DateOfAdmission_new)),0) as AverageLengthOfStay\r\nFROM health_care_dataset.healthcare_dataset;\r\n"
      }
     ]
    }
   ]
  },
  {
   "title": "Hospital and Doctor Performance",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 1 },
   "collapsed": true,
   "panels": [
    {
     "title": "Number of patients treated by each doctor",
     "type": "table",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 2 },
     "targets": [
      {
       "dataset": "health_care_dataset",
       "rawSql": "SELECT Doctor, COUNT(*) as PatientCount\r\nFROM health_care_dataset.healthcare_dataset \r\nGROUP BY Doctor\r\nORDER BY PatientCount DESC;\r\n"
      }
     ]
    },
    {
     "title": "Admissions by Hospital",
     "type": "table",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 10 },
     "targets": [
      {
       "dataset": "health_care_dataset",
       "rawSql": "SELECT Hospital, COUNT(*) as AdmissionCount\r\nFROM health_care_dataset.healthcare_dataset \r\nGROUP BY Hospital\r\nORDER BY AdmissionCount DESC;\r\n"
      }
     ]
    }
   ]
  },
  {
   "title": "Financial Data",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 2 },
   "collapsed": true,
   "panels": [
    {
     "title": "Avg Billing Amount Per Medical Condition",
     "type": "barchart",
     "gridPos": { "h": 8, "w": 10, "x": 0, "y": 11 },
     "targets": [
      {
       "dataset": "health_care_dataset",
       "rawSql": "SELECT AVG(`Billing Amount`), `Medical Condition` FROM health_care_dataset.healthcare_dataset GROUP BY `Medical Condition`;"
      }
     ]
    }
   ]
  },
  {
   "title": "Admission Details",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 3 },
   "collapsed": true,
   "panels": [
    {
     "title": "Admission Types",
     "type": "barchart",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 4 },
     "targets": [
      {
       "dataset": "health_care_dataset",
       "rawSql": "SELECT `Admission Type`, COUNT(*)  as TypeCount FROM health_care_dataset.healthcare_dataset GROUP BY `Admission Type`; "
      }
     ]
    },
    {
     "title": "Admissions Over Time",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 12 },
     "targets": [
      {
       "dataset": "health_care_dataset",
       "rawSql": "SELECT DateOfAdmission_new, COUNT(*) FROM health_care_dataset.healthcare_dataset GROUP BY DateOfAdmission_new ORDER BY DateOfAdmission_new;"
      }
     ]
    }
   ]
  },
  {
   "title": "Medical Conditions",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 4 },
   "collapsed": true,
   "panels": [
    {
     "title": "Common Medical Conditions",
     "type": "barchart",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 13 },
     "targets": [
      {
       "dataset": "health_care_dataset",
       "rawSql": "SELECT `Medical Condition`, COUNT(*) as ConditionCount\r\nFROM health_care_dataset.healthcare_dataset\r\nGROUP BY `Medical Condition`\r\n"
      }
     ]
    }
   ]
  },
  {
   "title": "Patient Demographics",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 5 },
   "collapsed": true,
   "panels": [
    {
     "title": "Gender Distribution",
     "type": "barchart",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 6 },
     "targets": [
      {
       "dataset": "health_care_dataset",
       "rawSql": "SELECT Gender, COUNT(Gender) as PatientCount FROM health_care_dataset.healthcare_dataset GROUP BY Gender;"
      }
     ]
    },
    {
     "title": "Age Distribution",
     "type": "histogram",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 14 },
     "targets": [
      {
       "dataset": "health_care_dataset",
       "rawSql": "SELECT Age, COUNT(*) as PatientCount FROM health_care_dataset.healthcare_dataset GROUP BY Age ORDER BY Age;"
      }
     ]
    }
   ]
  }
 ]
}